# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('travel_date_from', models.CharField(max_length=45)),
                ('travel_date_to', models.CharField(max_length=45)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_trips', to='travel_buddy_app.User')),
                ('joined_by', models.ManyToManyField(related_name='joined', to='travel_buddy_app.User')),
            ],
        ),
    ]
