# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='added_by',
            field=models.CharField(max_length=45),
        ),
    ]
