# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0003_auto_20171120_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_trips', to='travel_buddy_app.User'),
        ),
    ]
